# Change these first
owner: chennien # Your GitHub organization or username, where this repository lives
repo: status.appsoda.net # The name of this repository

sites:
  - name: appSoda
    url: https://appsoda.net/robots.txt
    icon: https://appsoda.net/favicon.ico


status-website:
  theme: light

  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.appsoda.net
  # baseUrl: /your-repo-name
  favicon: https://appsoda.net/favicon.ico
  logoUrl: https://appsoda.net/img/favicon.png
  name: appSoda
  introTitle: "**appsoda.net** System Status"
  introMessage: "[appsoda.net](https://appsoda.net) | Turn your favorite websites into desktop apps"
  scripts:
    - src: https://appsoda.net/js/analytics.min.js
      async: true

  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://appsoda.net

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
